<a href="https://colab.research.google.com/github/heugyu/notebook/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Pytorch 패키지 설치
!pip3 install torch

In [0]:
import torch

In [7]:
x = torch.tensor([[1,2,3,], [4,5,6], [7,8,9]])
print(x.size())
print(x.shape)
# 차원 정보 
print(x.ndimension())

# unsqueeze(), squeeze(), view() 함수로 텐서의 랭크와 shape의 인위적 변경 가능 

torch.Size([3, 3])
torch.Size([3, 3])
2


In [9]:
# 정규분포에서 무작위로 값을 뽑아 텐서를 생성하는 randn()
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

print(w.size())
print(x.size())

print(w)
print(x)

# 행렬곱은 torch.mm() 함수 사용 -> matmul
wx = torch.mm(w,x)
print(wx.size())
print(wx)

# (5, 3) * (3 ,2) = (5, 2)

torch.Size([5, 3])
torch.Size([3, 2])
tensor([[-0.5459,  0.1215, -0.6685],
        [-0.3041, -0.0787, -1.6572],
        [-0.0633, -1.0126, -0.3969],
        [ 0.4379, -0.3911,  0.1603],
        [ 0.5228,  0.0526,  0.3264]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([5, 2])
tensor([[ -3.5240,  -4.6168],
        [ -8.8260, -10.8659],
        [ -5.0854,  -6.5582],
        [  0.0660,   0.2732],
        [  2.3127,   3.2146]])


### Autograd
- 데이터의 정답(ground_truth)과 모델이 예측한 결과의 차이를 산술적으로 표현한 거리(distance)
- 학습 데이터로 계산한 거리들의 평균을 오차(loss)
- 오차가 작은 모델일수록 정확한 모델 
- 오차를 최소화 하는 알고리즘 중 기본 -> 경사하강법(gradient decent)
- 경사하강법, 오차를 수학 함수로 표현 후 미분하여 함수의 기울기를 구해 loss가 최소가 되는 방향을 찾는 알고리즘
- **Pytorch의 Autograd는 미분 계산을 자동화 하여 경사 하강법을 구현 하는 수고를 덤**

In [11]:
# requires_grad = True
# Pytorch의 Autograd 기능이 자동으로 계산할 때 w에 대한 미분값을 w.grad에 저장
w = torch.tensor(1.0, requires_grad=True)
a = w * 3
l = a ** 2

# l을 w로 미분하려면 연쇄법칙을 이용하여 a와 w로 차례대로 미분 
# backward() 함수
l.backward()
print(w.grad)

tensor(18.)
